# Generated by Django 4.2.2 on 2023-06-13 07:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('chapter_number', models.IntegerField()),
                ('chapter', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=2)),
                ('file', models.FileField(upload_to=api.models.ReviewNote.get_upload_path)),
            ],
        ),
    ]
